import { Instalment } from './app.model';

export const INSTALMENTS: Instalment[] = [
  {id: 25, value: 'SELECT', name: 'Selecionar'},
  {id: 1, value: 'ONE_INSTALMENT', name: 'À Vista'},
  {id: 2, value: 'TWO_INSTALMENT_NO_INTEREST', name: '2x sem juros'},
  {id: 3, value: 'THREE_INSTALMENT_NO_INTEREST', name: '3x sem juros'},
  {id: 4, value: 'FOUR_INSTALMENT_NO_INTEREST', name: '4x sem juros'},
  {id: 5, value: 'FIVE_INSTALMENT_NO_INTEREST', name: '5x sem juros'},
  {id: 6, value: 'SIX_INSTALMENT_NO_INTEREST', name: '6x sem juros'},
  {id: 7, value: 'SEVEN_INSTALMENT_NO_INTEREST', name: '7x sem juros'},
  {id: 8, value: 'EIGHT_INSTALMENT_NO_INTEREST', name: '8x sem juros'},
  {id: 9, value: 'NINE_INSTALMENT_NO_INTEREST', name: '9x sem juros'},
  {id: 10, value: 'TEN_INSTALMENT_NO_INTEREST', name: '10x sem juros'},
  {id: 11, value: 'ELEVEN_INSTALMENT_NO_INTEREST', name: '11x sem juros'},
  {id: 12, value: 'TWELVE_INSTALMENT_NO_INTEREST', name: '12x sem juros'},
  {id: 13, value: 'TWO_INSTALMENT_WITH_INTEREST', name: '2x com juros'},
  {id: 14, value: 'THREE_INSTALMENT_WITH_INTEREST', name: '3x com juros'},
  {id: 15, value: 'FOUR_INSTALMENT_WITH_INTEREST', name: '4x com juros'},
  {id: 16, value: 'FIVE_INSTALMENT_WITH_INTEREST', name: '5x com juros'},
  {id: 17, value: 'SIX_INSTALMENT_WITH_INTEREST', name: '6x com juros'},
  {id: 18, value: 'SEVEN_INSTALMENT_WITH_INTEREST', name: '7x com juros'},
  {id: 19, value: 'EIGHT_INSTALMENT_WITH_INTEREST', name: '8x com juros'},
  {id: 20, value: 'NINE_INSTALMENT_WITH_INTEREST', name: '9x com juros'},
  {id: 21, value: 'TEN_INSTALMENT_WITH_INTEREST', name: '10x com juros'},
  {id: 22, value: 'ELEVEN_INSTALMENT_WITH_INTEREST', name: '11x com juros'},
  {id: 23, value: 'TWELVE_INSTALMENT_WITH_INTEREST', name: '12x com juros'},
];
